### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by newpost** [davidelettieri/auto-tostring#5]

**Comment by davidelettieri** [comment]
Let me know if this is enough 
[Video](https://www.loom.com/share/ad3fa5e155a145ec833c70169717efdc?sid=98d619ba-4637-424e-8790-bfcceece6d0b)

**Comment by newpost** [comment]
·         Thank you very much!It work well,but Why is it not included in the readme file?

**Comment by newpost** [comment]
·         Thank you very much!It work well,but Why is it user guide in the readme file?

**Comment by newpost** [comment]
Thank you very much!It work well,But If you don't tell me, how will I know in other ways?

**Comment by davidelettieri** [comment]
There is a short description with a screenshot in the markeplace but I'll update the readme with more informations.

https://marketplace.visualstudio.com/items?itemName=DavideLettieri.AutoToString

**Comment by mynote** [comment]
Video doesnt work anymore.

**Comment by davidelettieri** [comment]
I'm out of town now. I will check this in the next couple of days.

**Comment by davidelettieri** [comment]
Fixed the link, thanks! @mynote 

[Here also](https://www.loom.com/share/ad3fa5e155a145ec833c70169717efdc?sid=98d619ba-4637-424e-8790-bfcceece6d0b)
