### ISSUE TITLE
Can ToString be omitted for ValueType?

### ISSUE THREAD

**Issue by dongbeifeng** [davidelettieri/auto-tostring#9]
Can we use this

``` csharp {3}
    public string GetPrintedValueForCSharp()
    {
        return IsValueType ? $"{{nameof({Name})}}={{{Name}}}" : $"{{nameof({Name})}}={{{Name}}}";
    }
```
instead of this

``` csharp {3}
    public string GetPrintedValueForCSharp()
    {
        return IsValueType ? $"{{nameof({Name})}}={{{Name}.ToString()}}" : $"{{nameof({Name})}}={{{Name}}}";
    }
```

**Comment by davidelettieri** [comment]
Hi, thanks for your feedback. I did some benchmark and the using the additional ToString seems to be slightly faster.

I prefer to keep it this way, I saw you forked the repo it should be easy to modify the extension for your own use. You just need to install the appropriate visual studio workload for developing extensions.

**Comment by dongbeifeng** [comment]
Thanks for your excellent work.
